# Metadados das provas (extraídos dos cadernos e dos arquivos de gabarito).
# ordem: ano crescente; provas sem ano identificado ao final, na ordem dos arquivos.
NI = "não identificado"
PROVAS = [
 dict(arq="P1/sgapcac_c_1_perito_caderno_a.pdf", concurso="Concurso Público – SGA/PCAC (Caderno A)",
      orgao="Polícia Civil do Estado do Acre – Secretaria de Estado da Gestão Administrativa", cargo="Cargo 1: Perito Médico-Legal",
      banca="UnB/CESPE", ano="2006", fonte="PC-AC – Perito Médico-Legal – CESPE – 2006"),
 dict(arq="p2/prova_ml02_tipo_001.pdf", concurso="Concurso Público para provimento de cargos de Médico Legista 3ª Classe (Caderno ML02, Tipo 001)",
      orgao="Governo do Estado do Maranhão – Secretaria de Estado de Planejamento, Orçamento e Gestão", cargo="Médico Legista 3ª Classe",
      banca="Fundação Carlos Chagas (FCC)", ano="2006", fonte="MA – Médico Legista 3ª Classe – FCC – 2006"),
 dict(arq="P1/prova_pcdf_perito_2008_funiversa.pdf", concurso="Concurso Público 4/2007 – PCDF",
      orgao="Polícia Civil do Distrito Federal", cargo="401 – Perito Médico-Legista",
      banca="Fundação Universa", ano="2008", fonte="PCDF – Perito Médico-Legista – Fundação Universa – 2008", scanned=True),
 dict(arq="P1/prova8.pdf", concurso="Concurso Público – Edital 001/2008",
      orgao="Instituto Geral de Perícias de Santa Catarina – IGP/SC", cargo="Perito Médico-Legista – Médica (Prova Tipo 1)",
      banca="GPG Concursos", ano="2008", fonte="IGP/SC – Perito Médico-Legista – GPG Concursos – 2008"),
 dict(arq="p2/s01_medico_perito_legista_de_1a_classe.pdf", concurso="Concurso Público PEFOCE – 2011 (itens Certo/Errado)",
      orgao="Perícia Forense do Estado do Ceará – PEFOCE", cargo="Médico Perito Legista de 1ª Classe",
      banca="FUNCAB", ano="2011", fonte="PEFOCE – Médico Perito Legista de 1ª Classe – FUNCAB – 2011", ce=True),
 dict(arq="p2/medico_legista (3).pdf", dup="p2/policia_civil_medico_legista_caderno_01.pdf", concurso="Concurso Público 2012 – Polícia Civil (Prova Tipo 1 – Branca)",
      orgao="Polícia Civil do Estado do Maranhão", cargo="Médico Legista",
      banca="FGV", ano="2012", fonte="PC-MA – Médico Legista – FGV – 2012"),
 dict(arq="p2/caderno_30_medico_legista_a_20130528_143535.pdf", concurso="Concurso Público – Provimento 2013/1 – Edital 01/13 (Caderno 30, Gabarito A)",
      orgao="Polícia Civil de Minas Gerais – Academia de Polícia Civil", cargo="Médico Legista",
      banca="FUMARC", ano="2013", fonte="PCMG – Médico Legista – FUMARC – 2013"),
 dict(arq="p2/medico_legista_3_categoria.pdf", concurso="Concurso Público – Polícia Civil do Espírito Santo",
      orgao="Polícia Civil do Estado do Espírito Santo", cargo="Médico-Legista – 3ª Categoria",
      banca="FUNCAB", ano="2013", fonte="PC-ES – Médico-Legista 3ª Categoria – FUNCAB – 2013"),
 dict(arq="p2/prova_medico_legista_versao1.pdf", concurso="Concurso Público ML-1/2013 – Prova Preambular (Versão 1)",
      orgao="Polícia Civil de São Paulo – Academia de Polícia “Dr. Coriolano Nogueira Cobra”", cargo="Médico Legista",
      banca=NI, ano="2014", fonte="PC-SP – Médico Legista – Concurso ML-1/2013 – 2014"),
 dict(arq="p2/pv_conhec_espec_cargo_4_med_legista.pdf", concurso="Concurso Público SDS/PE – Conhecimentos Específicos",
      orgao="Secretaria de Defesa Social de Pernambuco – SDS/PE", cargo="Cargo 4: Médico Legista",
      banca="CESPE/CEBRASPE", ano="2016", fonte="SDS/PE – Médico Legista – CESPE/CEBRASPE – 2016"),
 dict(arq="P1/perito_medico_legista (3).pdf", concurso="Concurso Público nº 02/2017",
      orgao="Instituto-Geral de Perícias do Rio Grande do Sul – IGP-RS", cargo="Perito Médico-Legista",
      banca="Fundatec", ano="2017", fonte="IGP-RS – Perito Médico-Legista – Fundatec – 2017"),
 dict(arq="p2/perito_medico_legista (1).pdf", concurso="Concurso Público – Edital 001/2017 (Prova Tipo 1)",
      orgao="Instituto Geral de Perícias de Santa Catarina – IGP/SC", cargo="Perito Médico Legista",
      banca="IESES", ano="2017", fonte="IGP/SC – Perito Médico Legista – IESES – 2017"),
 dict(arq="p2/medico_legista (2).pdf", concurso="Concurso Público SSP/MA – Polícia Civil do Maranhão",
      orgao="Secretaria de Estado da Segurança Pública do Maranhão – Polícia Civil do Estado do Maranhão", cargo="Médico Legista (caderno 373_SSPMA_APC_003)",
      banca="CESPE/CEBRASPE", ano="2018", fonte="PC-MA – Médico Legista – CESPE/CEBRASPE – 2018"),
 dict(arq="p2/perito_medico_legista_de_3_classe_medico_legista.pdf", concurso="Concurso Público – Polícia Civil 2018 (Prova Tipo 01)",
      orgao="Polícia Civil do Estado do Piauí", cargo="Perito Médico Legista de 3ª Classe – Médico Legista",
      banca="NUCEPE/UESPI", ano="2018", fonte="PC-PI – Perito Médico Legista de 3ª Classe – NUCEPE – 2018"),
 dict(arq="p2/medico_legista (1).pdf", concurso="Concurso Público de Provas e Títulos – SAD/SEJUSP/CGP/POF-PML/2021",
      orgao="Polícia Civil do Estado de Mato Grosso do Sul", cargo="Perito Oficial Forense – Perito Médico Legista",
      banca=NI, ano="2021", fonte="PC-MS – Perito Médico Legista – 2021"),
 dict(arq="P1/perito_oficial_criminal_medico_legista_ou_medicina_legal.pdf", concurso="Concurso Público – Edital nº 002/2022-SEPLAG/SESP/MT",
      orgao="Perícia Oficial e Identificação Técnica de Mato Grosso – POLITEC/MT", cargo="Perito Oficial Médico-Legista – Perfil: Medicina Legal",
      banca=NI, ano="2022", fonte="POLITEC/MT – Perito Oficial Médico-Legista (Medicina Legal) – 2022"),
 dict(arq="P1/perito_oficial_criminal_medico_legista_ou_medicina_legal_psiquiatria.pdf", concurso="Concurso Público – Edital nº 002/2022-SEPLAG/SESP/MT",
      orgao="Perícia Oficial e Identificação Técnica de Mato Grosso – POLITEC/MT", cargo="Perito Oficial Médico-Legista – Perfil: Medicina Legal – Psiquiatria",
      banca=NI, ano="2022", fonte="POLITEC/MT – Perito Oficial Médico-Legista (Psiquiatria) – 2022"),
 dict(arq="p2/medico_legista_de_policia_civil (1).pdf", concurso="Concurso Público – Polícia Civil de Roraima (caderno 005 – Prova Objetiva)",
      orgao="Polícia Civil do Estado de Roraima", cargo="Médico Legista de Polícia Civil",
      banca="Fundação Vunesp", ano="2022", fonte="PC-RR – Médico Legista – Vunesp – 2022"),
 dict(arq="p2/medico_legista_de_3_classe_generalista.pdf", concurso="Concurso Público – Polícia Técnico-Científica de Goiás (Prova Tipo “A”)",
      orgao="Governo do Estado de Goiás – SEAD / Polícia Técnico-Científica", cargo="201 – Médico Legista de 3ª Classe – Geral",
      banca="IADES", ano="2024", fonte="PTC-GO – Médico Legista de 3ª Classe (Geral) – IADES – 2024"),
 dict(arq="p2/medico_legista_de_3_classe_especialista_em_psiquiatria.pdf", concurso="Concurso Público – Polícia Técnico-Científica de Goiás (Prova Tipo “U”)",
      orgao="Governo do Estado de Goiás – SEAD / Polícia Técnico-Científica", cargo="203 – Médico Legista de 3ª Classe – Especialista em Psiquiatria",
      banca="IADES", ano="2024", fonte="PTC-GO – Médico Legista de 3ª Classe (Psiquiatria) – IADES – 2024"),
 dict(arq="p2/medico_legista.pdf", concurso="Concurso Público – Edital nº 02/2024 (Prova Tipo 1 – Branca; aplicada em 26/01/2025)",
      orgao="Polícia Civil do Estado de Minas Gerais", cargo="Médico-Legista",
      banca="FGV", ano="2025", fonte="PCMG – Médico-Legista – FGV – 2025"),
 dict(arq="p2/medico_legista_de_policia_civil.pdf", concurso="Concurso Público – Curso de Formação (caderno 062)",
      orgao="Polícia Civil do Estado de Roraima", cargo="Curso de Formação – Médico Legista de Polícia Civil",
      banca=NI, ano="2025", fonte="PC-RR – Curso de Formação Médico Legista – 2025"),
 dict(arq="P1/perito_medico_legista (2).pdf", concurso="Concurso Público nº 01/2025",
      orgao="Instituto-Geral de Perícias do Rio Grande do Sul – IGP-RS", cargo="Perito Médico-Legista",
      banca="Fundatec", ano="2025", fonte="IGP-RS – Perito Médico-Legista – Fundatec – 2025"),
 dict(arq="P1/perito_medico_legista_de_policia_civil.pdf", concurso="Concurso Público SAEB 04/2022 – Avaliação Final do Curso de Formação",
      orgao="Departamento de Polícia Técnica da Bahia – DPT/BA", cargo="PML – Perito Médico Legista de Polícia Civil",
      banca="IBADE", ano=NI + " (gabarito final atualizado em 14/02/2025)", sortyear=2025, fonte="DPT/BA – Perito Médico Legista (Curso de Formação) – IBADE"),
 dict(arq="P1/perito_medico_legista_e_patologia.pdf", concurso="Concurso Público – Edital nº 02/2025 (Tipo 1 – Branca)",
      orgao="Polícia Civil do Estado do Piauí – Delegacia-Geral", cargo="Perito Médico Legista e Patologia",
      banca="FGV", ano="2026", fonte="PC-PI – Perito Médico Legista e Patologia – FGV – 2026"),
 dict(arq="P1/perito_medico_legista_e_psiquiatria.pdf", concurso="Concurso Público – Edital nº 02/2025 (Tipo 1 – Branca)",
      orgao="Polícia Civil do Estado do Piauí – Delegacia-Geral", cargo="Perito Médico Legista e Psiquiatria",
      banca="FGV", ano="2026", fonte="PC-PI – Perito Médico Legista e Psiquiatria – FGV – 2026"),
 dict(arq="p2/perito_medico_legista.pdf", concurso="Concurso Público – Edital nº 02/2025 (Tipo 1 – Branca)",
      orgao="Polícia Civil do Estado do Piauí – Delegacia-Geral", cargo="Perito Médico Legista (Geral)",
      banca="FGV", ano="2026", fonte="PC-PI – Perito Médico Legista (Geral) – FGV – 2026"),
 # sem ano identificado (ordem dos arquivos)
 dict(arq="P1/s22_01_perito_oficial_medico_legista_medico.pdf", dup="P1/s22_01_perito_oficial_medico_legista_medico (1).pdf", concurso="Concurso Público POLITEC/MT",
      orgao="Perícia Oficial e Identificação Técnica de Mato Grosso – POLITEC/MT", cargo="S22 – Perito Oficial Médico Legista – Médico",
      banca="FUNCAB", ano=NI, fonte="POLITEC/MT – Perito Oficial Médico Legista (S22) – FUNCAB"),
 dict(arq="P1/s23_01_perito_oficial_medico_legista_medico_psiquiatria (1).pdf", concurso="Concurso Público POLITEC/MT",
      orgao="Perícia Oficial e Identificação Técnica de Mato Grosso – POLITEC/MT", cargo="S23 – Perito Oficial Médico Legista – Médico Psiquiatra",
      banca="FUNCAB", ano=NI, fonte="POLITEC/MT – Perito Oficial Médico Legista Psiquiatra (S23) – FUNCAB"),
 dict(arq="p2/m29_p_medico_perito_legista.pdf", concurso="Concurso Público SESACRE (Médico) – Prova M29",
      orgao="Secretaria de Estado de Saúde do Acre – SESACRE", cargo="M29 – Médico Perito-Legista",
      banca="FUNCAB", ano=NI, fonte="SESACRE – Médico Perito-Legista (M29) – FUNCAB"),
 dict(arq="p2/medico_perito_legista_de_classe_a_nivel_i.pdf", concurso="Avaliação de Verificação de Aprendizagem (prova escrita objetiva)",
      orgao="Perícia Forense do Estado do Ceará – PEFOCE (identificado pelo nome do arquivo e pelo conteúdo)", cargo="Médico Perito Legista de Classe A, Nível I",
      banca=NI, ano=NI, fonte="PEFOCE – Médico Perito Legista Classe A Nível I – AVA"),
 dict(arq="p2/s01_v_medico_legista.pdf", concurso="Concurso Público – Polícia Civil de Rondônia (Prova V, código S01)",
      orgao="Polícia Civil do Estado de Rondônia", cargo="Médico Legista",
      banca="FUNCAB", ano=NI, fonte="PC-RO – Médico Legista – FUNCAB"),
]
